AWSTemplateFormatVersion: '2010-09-09'
Description: All resources which are shared among all versions of the passhelper

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: billing
          Value: passhelper
      AccessControl: Private
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}-passhelper"
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: S3 bucket for project resources
