AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Api routes

Parameters:
  Api:
    Description: Api id
    Type: String

  Integration:
    Description: Integration id
    Type: String

Resources:

  # Login/Logout routes
  GetLoginRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /login'
      Target: !Sub 'integrations/${Integration}'

  # Login/Logout routes
  GetLogoutRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /logout'
      Target: !Sub 'integrations/${Integration}'

  # App routes
  GetRootRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /'
      Target: !Sub 'integrations/${Integration}'

  GetIndexRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /index'
      Target: !Sub 'integrations/${Integration}'

  CreatePassportRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'POST /add'
      Target: !Sub 'integrations/${Integration}'

  AddPassportRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /add'
      Target: !Sub 'integrations/${Integration}'

  EditPassportRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /edit/{id}'
      Target: !Sub 'integrations/${Integration}'

  UpdatePassportRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'POST /edit/{id}'
      Target: !Sub 'integrations/${Integration}'

  DeletePassportRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'DELETE /edit/{id}'
      Target: !Sub 'integrations/${Integration}'

  GetCalenderRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /calender'
      Target: !Sub 'integrations/${Integration}'

  GetUsersRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'GET /users'
      Target: !Sub 'integrations/${Integration}'

  AddUserRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'POST /users'
      Target: !Sub 'integrations/${Integration}'

  DeleteUserRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'DELETE /users/{username}'
      Target: !Sub 'integrations/${Integration}'

  PatchUserAttributeValueEndpoint:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'PATCH /users/{username}/attributes/{attribute}/value/{value}'
      Target: !Sub 'integrations/${Integration}'
