name: Java CI with Gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 22 ]

    services:
      docker:
        image: docker:20.10.16
        options: --privileged  # Needed to enable Docker-in-Docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        name: Set up Graal ${{ matrix.java-version }}
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          set-java-home: 'true'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: build/test-results/test/*.xml
          fail_on_failure: true
          include_passed: false
          detailed_summary: true
