name: Native build and test

on: push

jobs:
  build-test:
    name: Native build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          set-java-home: 'true'

      - uses: gradle/actions/setup-gradle@v3

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - run: ./gradlew clean nativeTestCompile

      - uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: build/test-results/test/*.xml
          fail_on_failure: true
          include_passed: false
          detailed_summary: true
