name: Java CI with Gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 23 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Graal ${{ matrix.java-version }}
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          set-java-home: 'true'

      - uses: gradle/actions/setup-gradle@v3

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and Test
        run: ./gradlew clean nativeTestCompile

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: build/test-results/test/*.xml
          fail_on_failure: true
          include_passed: false
          detailed_summary: true
