name: Test Lambdas

on: push

jobs:

  build-image:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-        

      - id: image-name
        run: |
          uuid=$(uuidgen)
          echo "image=ttl.sh/${uuid}:1h" >> "$GITHUB_OUTPUT"

      - run: |
          docker buildx build \
          --platform linux/arm64 \
          --tag ${{ steps.image-name.outputs.image }} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
          --push .       

  test-api:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ${{ needs.build-image.outputs.image-name.image }}

      - run: sam build --use-container --template-file passhelper.cf.yaml ApiFunction --parameter-overrides IncludeHealthRoute=true

      - run: sam local invoke ApiFunction --env-vars src/test/resources/integration/api/env.json --event src/test/resources/integration/api/request.json

  test-notification:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ${{ needs.build-image.outputs.image-name.image }}

      - run: sam build --use-container --template-file passhelper.cf.yaml NotificationFunction

      - run: sam local invoke NotificationFunction --env-vars src/test/resources/integration/notification/env.json --event src/test/resources/integration/notification/request.json
